info:
  id: tianditu_province
  name: 天地图省级节点
  lastUpdated:
maps:
  天地图-江苏: !include 天地图-江苏.yml
  天地图-湖北: !include 天地图-湖北.yml
  天地图-浙江: !include 天地图-浙江.yml
  天地图-安徽（有偏移）: !include 天地图-安徽（有偏移）.yml
  天地图-江西: !include 天地图-江西.yml
  天地图-上海: !include 天地图-上海.yml
  天地图-广东: !include 天地图-广东.yml
  天地图-福建: !include 天地图-福建.yml
