info:
  id: extra
  name: 其他地图
  lastUpdated:
maps:
  谷歌地图: !include GoogleMap.yml
  # 谷歌地图CN: !include GoogleMapCN.yml
  ESRI: !include Esri.yml
  高德地图: !include Amap.yml
  Stamen Maps: !include Stamen.yml
  OpenRailwayMap: !include OpenRaliwayMap.yml
