name: Pack Config File

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  pack-config-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run Pack Scripts
        run: python scripts/pack.py
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 📦 pack config file
