name: Pack Config File

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  pack-config-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"

      - name: Run Pack Scripts
        run: uv run scripts/pack.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 📦 pack config file
